env:
  REPODEST: /home/builder/packages/${BUILDKITE_BRANCH}

steps:
  - label: ":package: + :s3:"
    branches: "master develop"
    command: 
      - "cd .apk/upmaru/compressor"
      - "abuild snapshot"
      - "abuild -r"
      - "s3cmd sync s3://artellectual.apk.build/packages/ /home/builder/packages/"
      - "abuild cleanoldpkg"
      - "s3cmd sync --delete-removed /home/builder/packages/ s3://artellectual.apk.build/packages/"